services:
  client:
    env_file:
      - ./client/.env.development
    build:
      context: ./client
      target: client-dev
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/local/app
      - /usr/local/app/node_modules
    depends_on:
      - backend

  backend:
    env_file:
      - ./backend/.env.development
    build:
      context: ./backend
      target: backend-dev
    volumes:
      - ./backend:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    env_file:
      - .env.postgres.development
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.pgadmin.development
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  postgres_data:
